const fs = require('fs');
const path = require('path');
const { glob } = require('glob');

/**
 * Build or update the .contexts/index.md file.
 * This is the master index of all .context.md files in the project.
 */
async function buildIndex(config) {
  const root = config._root || process.cwd();

  // Find all .context.md files
  const contextFiles = await glob('**/*.context.md', {
    cwd: root,
    ignore: ['node_modules/**', 'dist/**', 'build/**', '.contexts/**'],
    absolute: false,
  });

  if (contextFiles.length === 0) {
    return null;
  }

  // Categorize files
  const categories = {
    components: [],
    hooks: [],
    utils: [],
    contexts: [],
    types: [],
    other: [],
  };

  for (const file of contextFiles) {
    const content = fs.readFileSync(path.join(root, file), 'utf-8');
    const name = extractName(content, file);
    const type = extractType(content);
    const purpose = extractPurpose(content);

    const entry = {
      name,
      path: file,
      purpose: purpose || '',
    };

    switch (type) {
      case 'component':
        categories.components.push(entry);
        break;
      case 'hook':
        categories.hooks.push(entry);
        break;
      case 'util':
        categories.utils.push(entry);
        break;
      case 'context':
        categories.contexts.push(entry);
        break;
      case 'type':
        categories.types.push(entry);
        break;
      default:
        categories.other.push(entry);
    }
  }

  // Generate index content
  let index = '';
  index += '<!-- @contextify-ai index | auto-generated -->\n';
  index += `<!-- updated: ${new Date().toISOString()} -->\n`;
  index += `<!-- total: ${contextFiles.length} context files -->\n\n`;
  index += '# Project Context Index\n\n';
  index += 'This file is auto-generated by contextify-ai. ';
  index += 'It provides a map of all .context.md files in the project.\n\n';
  index += 'AI tools: read this file first to understand the project structure, ';
  index += 'then read individual .context.md files for component-level detail.\n\n';

  if (categories.components.length > 0) {
    index += '## Components\n\n';
    index += formatEntries(categories.components);
  }

  if (categories.hooks.length > 0) {
    index += '## Hooks\n\n';
    index += formatEntries(categories.hooks);
  }

  if (categories.utils.length > 0) {
    index += '## Utilities\n\n';
    index += formatEntries(categories.utils);
  }

  if (categories.contexts.length > 0) {
    index += '## Contexts\n\n';
    index += formatEntries(categories.contexts);
  }

  if (categories.types.length > 0) {
    index += '## Types\n\n';
    index += formatEntries(categories.types);
  }

  if (categories.other.length > 0) {
    index += '## Other\n\n';
    index += formatEntries(categories.other);
  }

  // Write the index
  const indexDir = path.join(root, '.contexts');
  if (!fs.existsSync(indexDir)) {
    fs.mkdirSync(indexDir, { recursive: true });
  }

  const indexPath = path.join(indexDir, 'index.md');
  fs.writeFileSync(indexPath, index, 'utf-8');

  return {
    path: indexPath,
    totalFiles: contextFiles.length,
    categories: Object.fromEntries(
      Object.entries(categories).map(([k, v]) => [k, v.length])
    ),
  };
}

function formatEntries(entries) {
  let result = '';
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    result += `- **${entry.name}**: \`${entry.path}\``;
    if (entry.purpose) {
      result += ` - ${entry.purpose}`;
    }
    result += '\n';
  }
  result += '\n';
  return result;
}

function extractName(content, filePath) {
  const match = content.match(/^# (.+)$/m);
  if (match) return match[1].trim();
  return path.basename(filePath, '.context.md');
}

function extractType(content) {
  const match = content.match(/type: (component|hook|util|context|type)/);
  return match ? match[1] : 'other';
}

function extractPurpose(content) {
  const match = content.match(/## Purpose\n\n(.+?)(?:\n\n|\n##)/s);
  if (match) {
    // Take first sentence only
    const firstSentence = match[1].trim().split(/\.\s/)[0];
    return firstSentence.length > 120
      ? firstSentence.slice(0, 117) + '...'
      : firstSentence + '.';
  }
  return null;
}

module.exports = { buildIndex };
